### ISSUE TITLE
Add new observable variables

### ISSUE THREAD

**Issue by Geph** [whimc/Science-Tools#25]
/magnetic_field (strong, moderate, weak)
/gravity (relative to earth, use # units in G's)
/rotational_period or /day (number, on decimal unit is hours)
/orbital_period or /year (whole number, unit is days)
/planet_radius or /radius (whole number, km or miles)
/axis-tilt or /tilt (number, one decimal use ° for units)
/tides (empty string)

**Comment by jackah2** [comment]
This can all be done through the config now! I think this task is better suited to be on ClickUp.

**Comment by Geph** [comment]
Got it, moving it over.
