### ISSUE TITLE
Add "alias" variable

### ISSUE THREAD

**Issue by Geph** [whimc/Science-Tools#30]
Add a variable that can be used in the config to allow for different command words to do the same thing. For instance /airflow could be set as an alias for /wind, rather than making a whole new set of variables. This would be helpful to allow for shortened commands like /temp or /emrad or even anticipating spelling errors with something like /preshir

**Comment by Geph** [comment]
Alias mapping ideas:

/altitude -> /height
/atmosphere -> /ozone
/oxygen -> /air
/pressure -> /air_pressure
/radiation_em -> /emrad
/radiation_particle -> /radiation_nuclear, /nuclear
/temperature -> /temp
/airflow -> /wind
/radius -> /diameter
/magnetic_field -> /solar_wind
/day -> /rotational_period
/year -> /orbital_period
/tilt -> /axis_tilt, /axial_tilt
/tides -> /tidal_variance, /ocean_level

**Comment by jackah2** [comment]
Example config section:
```yml
tools:
  TIDES:
    aliases: [tide_variance, ocean_level]
```
