### ISSUE TITLE
Create {weather_clear} and {time_of_day} as variables for use in config file

### ISSUE THREAD

**Issue by Geph** [whimc/Science-Tools#31]
Could be just simple variables so we can assign different temperatures by time, like
world:
  mars:
     default-measurement: ____
     day: ____
     night: ____

day: would be the max value reached by noon on a given world, and then night: would be the minimum reached at midnight; values would be something like (day - night / 12 hr or equivalent of time) * actual time.

**Comment by jackah2** [comment]
A variety of new placeholders like `{TIME_TICKS}`, `{HOURS_TO_NOON}`, etc. would work better

**Comment by jackah2** [comment]
I'll also add a placeholder for weather: `{WEATHER_CLEAR}` which will return `1` if the weather is clear and `0` otherwise.
